name: Build GitHub page

on:
    push:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Cache yarn packages
              uses: actions/cache@v2
              with:
                  path: |
                      .yarn/cache
                  key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

            - name: Install dependencies & build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn
                  yarn build
                  # Prevent GitHub from trying to use Jekyll
                  touch public/.nojekyll
                  echo "app-builder.runcitadel.space" > public/CNAME
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./public
                  github_token: ${{ secrets.GITHUB_TOKEN }}
